### ISSUE TITLE
[Bug Report] Cannot create a new fate character

### ISSUE THREAD

**Issue by lordnull** [Morgul/rpgkeeper#44] opened 2020-05-03 21:36 UTC
server version: v2.0.0-beta.10

Fresh install and run using `yarn:watch` for client and `yarn start` for server. Signed in using google. Attempted to create a new fate core character. Client logs indicate 422 http error code. No error displayed on client.

Server output below:
```
POST 422 '/': AjvValidationError: ValidationError: /name: minLength should NOT be shorter than 1 characters.
    at validate (/Users/null/src/rpgkeeper/server/utils/ajvValidator.js:39:23)
    at /Users/null/src/rpgkeeper/server/routes/middleware/validation.js:59:13
    at /Users/null/src/rpgkeeper/server/routes/utils/router.js:222:9
    at Layer.handle [as handle_request] (/Users/null/src/rpgkeeper/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/null/src/rpgkeeper/node_modules/express/lib/router/route.js:137:13)
    at ensureAuthenticated (/Users/null/src/rpgkeeper/server/routes/utils/router.js:167:9)
    at Layer.handle [as handle_request] (/Users/null/src/rpgkeeper/node_modules/express/lib/router/layer.js:95:5)
    at next (/Users/null/src/rpgkeeper/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/Users/null/src/rpgkeeper/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/Users/null/src/rpgkeeper/node_modules/express/lib/router/layer.js:95:5)
    at /Users/null/src/rpgkeeper/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/Users/null/src/rpgkeeper/node_modules/express/lib/router/index.js:335:12)
    at next (/Users/null/src/rpgkeeper/node_modules/express/lib/router/index.js:275:10)
    at Function.handle (/Users/null/src/rpgkeeper/node_modules/express/lib/router/index.js:174:3)
    at router (/Users/null/src/rpgkeeper/node_modules/express/lib/router/index.js:47:12)
    at Layer.handle [as handle_request] (/Users/null/src/rpgkeeper/node_modules/express/lib/router/layer.js:95:5)
    request: {
      "method": "POST",
      "url": "/",
      "body": {
        "system": "fate",
        "name": "",
        "description": "",
        "portrait": "",
        "thumbnail": "",
        "color": "#5a139a",
        "campaign": "",
        "details": {
          "aspects": [
            {
              "type": "high concept",
              "detail": ""
            },
            {
              "type": "trouble",
              "detail": ""
            }
          ],
          "extras": "",
          "fatePoints": {
            "current": 0,
            "refresh": 0
          },
          "mentalStress": [
            false,
            false,
            false,
            false
          ],
          "physicalStress": [
            false,
            false,
            false,
            false
          ],
          "skills": [],
          "stunts": []
        }
      },
      "query": {}
    }
```

**Comment by Morgul** [comment] 2020-05-04 14:45
I wasn't able to reproduce this locally, but then I actually _read_ the error, and the problem is that you didn't name your character, and that's required. (The error actually tells you that, `"ValidationError: /name: minLength should NOT be shorter than 1 characters."`).

A few points: 

1. Currently the UI doesn't pipe errors back to the client; it's on my todo list, but the console is the best we've got, atm. (I know, terrible user experience, but at the time I was converting that code, bootstrap-vue didn't have a built in way to pop an error, and I didn't feel like building one. Since that exists now, I can add it pretty easily.)

2. Clearly the form shouldn't let you proceed if you don't put in the required fields. I skipped over form validation when I converted to bootstrap-vue since I was lazy. That totally needs to be added, jeeze.

I will split 1 and 2 out into their own items, and close this.

**Closed by Morgul** 2020-05-04 14:45 UTC
Labels: bug, needs review
